### ISSUE TITLE
Let the user choose to download folders as zip

### ISSUE THREAD

**Issue by JohnnyLAmpAz** [rssws/moodle-dl-ext#24]
The idea is to place a checkbox in the UI to let the user choose whether to download the folders as zip file or not.

Like this:

  □ Download folders as zip file

In this way, when chosen to do so, downloading zip file from `https://<your_moodle>/mod/folder/download_folder.php?id=<folder_id>` would preserve the folder's file structure.

**Comment by rssws** [comment]
Hi,

Sorry for the late reply. About your suggestion, I find it hard for users to understand what downloading as a zip file actually means. The extension itself also packs everything into a zip file. Although, I know you mean the button or the downloading URL provided by moodle. But again, I generally think supporting downloading some specific folder is just a feature good to have, as the user probably wants something more than that such as downloading the whole course.

Unless you can find out a clean solution to support preserving the subfolder structure for all pages, I would rather not add this feature which may confuse the user and make the extension less straightforward. 😃
